spring:
  datasource:
    hikari:
      max-lifetime: 58000
    username: root
    password: masterpw
    url: jdbc:mysql://192.168.255.105:3306/subway?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        format_sql: true
    show-sql: true
  config:
    activate:
      on-profile: prod

logging:
  level:
    nextstep.subway: info

management:
  metrics:
    export:
      cloudwatch:
        namespace: mond-page  # 해당 namespace로 Cloudwatch 메트릭을 조회 가능
        batch-size: 20
  endpoints:
    web:
      exposure:
        include: *
